USE [master]
GO

/****** Object:  Database [Knowledgebank]    Script Date: 1/12/2014 5:07:50 PM ******/
CREATE DATABASE [Knowledgebank]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Knowledgebank', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Knowledgebank.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Knowledgebank_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Knowledgebank_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Knowledgebank] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Knowledgebank].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Knowledgebank] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Knowledgebank] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Knowledgebank] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Knowledgebank] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Knowledgebank] SET ARITHABORT OFF 
GO

ALTER DATABASE [Knowledgebank] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Knowledgebank] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Knowledgebank] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Knowledgebank] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Knowledgebank] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Knowledgebank] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Knowledgebank] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Knowledgebank] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Knowledgebank] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Knowledgebank] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Knowledgebank] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Knowledgebank] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Knowledgebank] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Knowledgebank] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Knowledgebank] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Knowledgebank] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Knowledgebank] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Knowledgebank] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Knowledgebank] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Knowledgebank] SET  MULTI_USER 
GO

ALTER DATABASE [Knowledgebank] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Knowledgebank] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Knowledgebank] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Knowledgebank] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Knowledgebank] SET  READ_WRITE 
GO


